// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZlbbMEsvhk-A2uKETcqfTTGIgCwDDnw',
    appId: '1:889632764652:web:699cdd5c853183fcc82bc9',
    messagingSenderId: '889632764652',
    projectId: 'small-biz-social-30ff3',
    authDomain: 'small-biz-social-30ff3.firebaseapp.com',
    storageBucket: 'small-biz-social-30ff3.appspot.com',
    measurementId: 'G-7RR2TC03CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vmoovh3EyYcomBqVBQzIWkXJ7wm4ruc',
    appId: '1:889632764652:android:fc1fb1e4dd778cf7c82bc9',
    messagingSenderId: '889632764652',
    projectId: 'small-biz-social-30ff3',
    storageBucket: 'small-biz-social-30ff3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5apP6MRc2t1AIwLyRYCCoxDy1Y0nVj1c',
    appId: '1:889632764652:ios:4770878317dcf77ec82bc9',
    messagingSenderId: '889632764652',
    projectId: 'small-biz-social-30ff3',
    storageBucket: 'small-biz-social-30ff3.appspot.com',
    iosBundleId: 'com.social.smallbizsocial',
  );
}
